### ISSUE TITLE
PH Support: NFTunes not opening PH Data NFT

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#373] opened 2024-04-14 13:00 UTC
We have a Data NFT-PH music data nft collection:
https://devnet-explorer.multiversx.com/collections/OASMUSICPL-47b186

It's been setup in Explorer.

1. It works in the Data Wallet page
![image](https://github.com/Itheum/explorer-dapp/assets/743169/ba6d4c1a-7b5b-44d3-a0b6-be0eadfe92ed)

2. BUT does not work in the NF.Tunes page
<img width="1428" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/e4c51425-078c-43eb-9213-879ff6179450">

**Comment by damienen** [comment] 2024-04-15 08:01
Can't reproduce. Closing until can be done so

**Closed by damienen** 2024-04-15 08:01 UTC
Labels: bug
