### ISSUE TITLE
Relaunching a playlist throws cors errors in console - intermittently reproduceable.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#182] opened 2023-09-21 18:44 UTC
This is seen when relaunching the playlist within explorer NF-Tunes app.

![Image](https://github.com/Itheum/explorer-dapp/assets/121969933/77a2cf13-1e48-48a0-9b54-d32cc8a7b5b4)

**Comment by 911-Benedek-RobertGeorge** [comment] 2023-09-22 09:26
Cors and 500 bug is happening when fetching second song, the 403 is from happening when trying to fetch the img of the first song,
 There is console.log(err) in catch, but the error is handled.

**Comment by newbreedofgeek** [comment] 2023-09-22 09:37
ok.. tnx it's fine.

@fuzzyduke the CORs error is coming because the 2nd song is over 4.5MB and the data marshal is erroring out.. but the error is "handled" by the UI so it's not an issue. as the UI does not break

**Comment by damienen** [comment] 2023-09-22 10:45
Perfect then. This is expected behavior, so I am closing this

**Closed by damienen** 2023-09-22 10:45 UTC
