### ISSUE TITLE
Error seen while Launch time capsule data NFT on explorer.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#297] opened 2024-02-29 09:29 UTC
Launch time capsule data NFT on explorer. Below error is seen

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/4f0a8446-80b7-4706-9f19-bbbbf385c8b2)

**Comment by damienen** [comment] 2024-03-01 08:34
I was not able to reproduce using extension @fuzzyduke

**Comment by damienen** [comment] 2024-03-01 10:00
Moving to 1.13.0 so we don't forget to keep this in check, but it seems non reproducable

**Comment by damienen** [comment] 2024-03-05 06:44
We could do better error handling here

**Comment by newbreedofgeek** [comment] 2024-04-09 06:39
until we can repro... we should close it

**Closed by newbreedofgeek** 2024-04-09 06:39 UTC
