### ISSUE TITLE
NF Tunes renders a blank page upon launching a data NFT.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/explorer-dapp#205] opened 2023-10-08 08:58 UTC
NF Tunes renders a blank page upon launching a data NFT.
https://test.explorer.itheum.io/

Steps
1. Browse to NF-Tunes
2. Launch a data NFT via NF-Tunes app.
3. The song can be heard but the app/popup renders as a blank page.

![image](https://github.com/Itheum/explorer-dapp/assets/121969933/3415cb6c-33a0-487b-b11e-6ca5efff5dcb)

**Comment by damienen** [comment] 2023-10-09 05:53
This is caused by cache from an older version. We are working on cache busting. But closing

**Closed by damienen** 2023-10-09 05:53 UTC
