### ISSUE TITLE
bad display of the data nfts in wallet

### ISSUE THREAD

**Issue by 911-Benedek-RobertGeorge** [Itheum/explorer-dapp#246] opened 2023-12-04 16:23 UTC
In the wallet , check a data-nft , music data nft , then open a data nft that requires "Always allow pop-ups" ( https://test.datadex.itheum.io/datanfts/marketplace/DATANFTFT-e0b917-03 ) 
then try to open again a music data nft or trailbrazer

will get this display instead of the json file
![Image](https://github.com/Itheum/explorer-dapp/assets/72063093/7e0edc26-36bf-4aa4-988e-643a51210ec7)

**Comment by damienen** [comment] 2023-12-14 21:21
Can't reproduce anymore on @Enciusan 's branch after his fix. Solved. Closing.

**Closed by damienen** 2023-12-14 21:21 UTC
